namespace ECommerceAPI.Infrastructure.Operations
{
    public static class NameOperation
    {
        public static string CharacterRegulatory(string name)
        => name.Replace("!", "")
                .Replace("`", "")
                .Replace("~", "")
                .Replace("@", "")
                .Replace("#", "")
                .Replace("$", "")
                .Replace("%", "")
                .Replace("^", "")
                .Replace("&", "")
                .Replace("*", "")
                .Replace("(", "")
                .Replace(")", "")
                .Replace("_", "")
                .Replace("+", "")
                .Replace("=", "")
                .Replace("[", "")
                .Replace("{", "")
                .Replace("]", "")
                .Replace("}", "")
                .Replace("|", "")
                .Replace(";", "")
                .Replace(":", "")
                .Replace("'", "")
                .Replace("", "")
                .Replace(",", "")
                .Replace("<", "")
                .Replace(".", "")
                .Replace(">", "")
                .Replace("/", "")
                .Replace("Ö", "O")
                .Replace("ö", "o")
                .Replace("Ğ", "G")
                .Replace("ğ", "g")
                .Replace("I", "İ")
                .Replace("ı", "i")
                .Replace("ə", "a")
                .Replace("Ə", "A")
                .Replace("Ç", "C")
                .Replace("ç", "ç")
                .Replace("Ş", "S")
                .Replace("ş", "ş")
                .Replace("№", "");

    }
}
